settings:
  name: Satori CI Playbooks
  image: python
  example: satori local ./ --report --output

playbooks:
  - pip install satori-ci >>/dev/null 2>>/dev/null; satori playbooks --public

# Contents: while read line; do echo "satori://$line"; echo "------------------------------";cat $line; echo "--------------------------------------------------------------------------------"; echo ""; done<<<"`find ./ *.yml|grep -v ".git\|.satori"|grep yml|sed -e 's/\.\/\///g'`" > playbooks.txt
# List: find ./ -name "*.yml"|grep -v "github\|\.satori\|llm\|swift\|all\.yml"|sed -e 's/\.\/\///g'|awk '{print "  - satori://"$1}'|sort -u
tests:
  assertStdout: False
  name:
    - find . -name "*.yml" ! -path "./.*" -exec grep -L "name:" {} \;
  description:
    - find . -name "*.yml" ! -path "./.*" -exec grep -L "description:" {} \;
  author:
    - find . -name "*.yml" ! -path "./.*" -exec grep -L "author:" {} \;
  author_item:
    - find . -name "*.yml" ! -path "./.*" -exec grep -H "author:" -A1 {} \; | grep ":.*\-" | grep -v "https"
  example:
    - find . -name "*.yml" ! -path "./.*" -exec grep -L "example:" {} \;
  gallery:
    - find . -name "*.yml" ! -path "./.*" -exec grep -L "gallery:" {} \;
  gallery_item:
    - find . -name "*.yml" ! -path "./.*" -exec grep -H "gallery:" -A1 {} \; | grep "\-" | grep -v "gallery\|https"
  image:
    - find . -name "*.yml" ! -path "./.*" -exec grep -L "image:" {} \;
  test:
    - find . -name "*.yml" ! -path "./.*" ! -name "all.yml" -exec grep -L "assert" {} \;
  noreport:
    - grep "example:" * -R|grep -v "report"|awk -F':' '{print $1}'

import:
  - satori://code/yamllint.yml
